services:
  app:
    build: .
    environment:
      MONGO_URI_DOCKER: ${MONGO_URI_DOCKER}
      MONGO_URI_TEST_DOCKER: ${MONGO_URI_TEST_DOCKER}
      REDIS_URL_DOCKER: ${REDIS_URL_DOCKER}
      REDIS_TIME_LIMIT: ${REDIS_TIME_LIMIT}
      ACCESS_TOKEN_KEY: ${ACCESS_TOKEN_KEY}
      REFRESH_TOKEN_KEY: ${REFRESH_TOKEN_KEY}
      ACCESS_TOKEN_EXPIRY: ${ACCESS_TOKEN_EXPIRY}
      REFRESH_TOKEN_EXPIRY: ${REFRESH_TOKEN_EXPIRY}
    ports: 
      - "3000:3000"
    depends_on: 
      - mongo
      - redis
  mongo:
    image: mongo:8
    command: mongod
    ports:
      - "27017:27017"
  redis:
    image: redis:7
    command: redis-server
    ports:
      - "6379:6379"