services:
  app:
    build: .
    environment:
      MONGO_URI_DOCKER: ${MONGO_URI_DOCKER}
      MONGO_URI_TEST_DOCKER: ${MONGO_URI_TEST_DOCKER}
      ACCESS_TOKEN_KEY: ${ACCESS_TOKEN_KEY}
      REFRESH_TOKEN_KEY: ${REFRESH_TOKEN_KEY}
      ACCESS_TOKEN_EXPIRY: ${ACCESS_TOKEN_EXPIRY}
      REFRESH_TOKEN_EXPIRY: ${REFRESH_TOKEN_EXPIRY}
    ports: 
      - "3000:3000"
    depends_on: 
      - mongo
  mongo:
    image: mongo:latest
    command: mongod
    ports:
      - "27017:27017"